# Generated by Django 4.2.5 on 2023-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, unique=True, verbose_name='URL-имя'),
        ),
    ]
